### ISSUE TITLE
询问视频如何下载

### ISSUE THREAD

**Issue by BingLau7** [X140Yu/Developing-iOS-9-Apps-with-Swift#15]
您好，我在你们的Readme中的百度云盘上只看到了1，2，3的视频，而没有后续的视频，想询问一下是没有更新呢还是需要自行下载，如果需要自行下载的话可否告诉一下下载方法，因为我只在iTunes上找到了视频却没有找到下载的方法。

另外，由衷感谢你们所做的工作。

**Comment by X140Yu** [comment]
我这里网速实在慢... 明天应该可以上传好。

视频都会上传的，只是时间问题，等等吧~

**Comment by BingLau7** [comment]
好的，谢谢~
