### ISSUE TITLE
网盘里的视频只有6，7的？

### ISSUE THREAD

**Issue by 02VC7** [X140Yu/Developing-iOS-9-Apps-with-Swift#16]
如题，上次下载了3，今天去看下只有6，7？

**Comment by X140Yu** [comment]
http://pan.baidu.com/s/1kVlf1wr 都在这里

**Comment by 02VC7** [comment]
额，天了噜，原来是我的网页显示有问题，把剩下的文件用空白遮住要下拉才看得到，我的锅。😂
