### ISSUE TITLE
lecture 2 翻译有问题

### ISSUE THREAD

**Issue by igit-cn** [X140Yu/Developing-iOS-9-Apps-with-Swift#19]
00:00:19,952 --> 00:00:23,553
because I know only about half of you know what MVC is, and
因为关于什么是 MVC 我知道可能不及你们.

应该是：因为我知道，你们中差不多只有一半知道MVC是什么

**Comment by X140Yu** [comment]
https://github.com/CS193P-Translation-Group/Developing-iOS-9-Apps-with-Swift/commit/e126b73cd7a176d1a02f0d1770cb0799f36b0ebc

fixed, thanks
