### ISSUE TITLE
没有第12

### ISSUE THREAD

**Issue by zjy199103** [X140Yu/Developing-iOS-9-Apps-with-Swift#28]
没有看到12的更新

**Comment by X140Yu** [comment]
在 iTunes U 里我也没有找到…

On Mon, Jul 04, 2016 at 1:43 PM, zjy199103 < notifications@github.com [notifications@github.com] > wrote:
没有看到12的更新

**Comment by zjy199103** [comment]
刚看了一下，好像有12

**Comment by wenchengxucool** [comment]
有12的视频 啊！！！https://www.youtube.com/watch?v=wBzzfaTj4vg
