### ISSUE TITLE
求更新百度云盘的视频

### ISSUE THREAD

**Issue by czqInNanjing** [X140Yu/Developing-iOS-9-Apps-with-Swift#29]
RT
iTunes下载太慢了，还是希望有云盘下载（Aria2大法好）
辛苦翻译的大家了

**Comment by X140Yu** [comment]
事实是，我搬了家，百度盘上传速度只有几十 k，我也很想上传，心有余力不足啊…

On Mon, Jul 04, 2016 at 4:36 PM, Qiang Chen < notifications@github.com [notifications@github.com] > wrote:
RT
iTunes下载太慢了，还是希望有云盘下载（Aria2大法好）
辛苦翻译的大家了

**Comment by igit-cn** [comment]
可以代上传，另外是不是忘记上传了12的英文字幕

**Comment by lengjian** [comment]
在iTunes目录里查看plist找到下载地址，folx开10个线程，我这8M网络可以满速

**Comment by leelongch** [comment]
求百度云链接 谢谢
