### ISSUE TITLE
是否能開放小量的翻譯？

### ISSUE THREAD

**Issue by ledtorch** [X140Yu/Developing-iOS-9-Apps-with-Swift#31]
因為看到現在似乎翻譯停滯，有些佔的缺已經3個月沒有更新了
不知道是還在校對還是有什麼問題
想請問能否開放小量的翻譯，例如200~300這樣
讓更多人參與也許可以加快進度？

**Comment by buginux** [comment]
现在这个项目已经由 SwiftGG 接管了，会加快翻译速度的，请耐心等候~

**Comment by Vernsu** [comment]
@buginux 
好像没什么进展，好久了，第三节课还没有翻译到

**Comment by X140Yu** [comment]
@ledtorch 可以直接评论 issue 领任务
