### ISSUE TITLE
求网盘更新视频

### ISSUE THREAD

**Issue by Archer-sys** [X140Yu/Developing-iOS-9-Apps-with-Swift#33]
我今天看iTunes u上好像已经更新到17了吧，能不能把后边的也传到网盘啊！这样保存下载会方便一些！

**Comment by ledtorch** [comment]
從youtube載比較快吧
https://www.youtube.com/watch?v=oTsg-uJfxD4&list=PLsJq-VuSo2k26duIWzNjXztkZ7VrbppkT&index=17

**Comment by Archer-sys** [comment]
我也想这样，不过我在墙里，youtube在外边啊！！

**Comment by ledtorch** [comment]
翻吧，花點小錢划算的
不想花錢免費的也是有不差的

**Comment by Archer-sys** [comment]
看来这能这样了啊！！！

**Comment by Archer-sys** [comment]
https://p1-u.itunes.apple.com/WebObjects/LZStudent.woa/ra/feed/COEME3ECEBSTAMUF
今天无意中发现的，复制到浏览器就可以看到所有的视频下载地址了！！！用迅雷下很快！！！建议以后itunes u的视频可以发一个这样的地址，网上就有获取这个地址地方法！比翻墙什么的要好一些（个人感觉）！！

**Comment by X140Yu** [comment]
@Archer-sys 太赞了，我也是才知道，谢谢！
