### ISSUE TITLE
求12集翻译...

### ISSUE THREAD

**Issue by honbolau** [X140Yu/Developing-iOS-9-Apps-with-Swift#34]
YouTube:  https://www.youtube.com/watch?v=wBzzfaTj4vg&list=PLsJq-VuSo2k26duIWzNjXztkZ7VrbppkT&index=12

**Comment by o1xhack** [comment]
同求~

**Comment by panjiulong** [comment]
求~~

**Comment by Vernsu** [comment]
正在看12集，不需要翻译就能看下去。因为主要是demo演示。

**Comment by X140Yu** [comment]
AutoLayout 的话，iOS 8 和 iOS 9 的区别不大，如果实在看不懂英语，可以先看 iOS 8 的，这个我们做过翻译。

https://github.com/SwiftGGTeam/Developing_iOS_8_Apps_With_Swift/blob/master/subtitles/8.%20View%20Controller%20Lifecycle%2C%20Autolayout.srt
