### ISSUE TITLE
百度云链接失效了 求更新

### ISSUE THREAD

**Issue by leelongch** [X140Yu/Developing-iOS-9-Apps-with-Swift#35]
百度云链接失效了 求更新，谢谢

**Comment by Eggego** [comment]
百度云链接失效了 求更新，谢谢

**Comment by leelongch** [comment]
百度云链接失效了 求更新，谢谢

**Comment by X140Yu** [comment]
@dengcheng92 [Download](https://github.com/SwiftGGTeam/Developing-iOS-9-Apps-with-Swift/blob/master/download.md)
