### ISSUE TITLE
由SwiftGGTeam接管之后，进度貌似就停滞了啊，一个月了没有任何更新

### ISSUE THREAD

**Issue by ChaselAn** [X140Yu/Developing-iOS-9-Apps-with-Swift#36]

**Comment by leelongch** [comment]
可以分享一下百度云链接吗  谢谢

**Comment by Vernsu** [comment]
@leelongch  去iTunes U下载啊，速度又不慢

**Comment by X140Yu** [comment]
@leelongch [Download](https://github.com/SwiftGGTeam/Developing-iOS-9-Apps-with-Swift/blob/master/download.md)
