### ISSUE TITLE
给个下载视频的地址吧

### ISSUE THREAD

**Issue by ghost320** [X140Yu/Developing-iOS-9-Apps-with-Swift#37]
我看到百度云已经失效了，知道翻译是个很辛苦的工作，所以这边说声字幕组辛苦了，也不催促，尽量精益求精。

这边只是想先下载一套原版的视频，用蹩脚的英文先看着，现在百度地址已经失效，无法下载原版视频了，能给个原版下载地址吗，谢啦

**Comment by Vernsu** [comment]
虽然你讲的挺动人。但我还是想说：
下载地址自己Google一下，第一条就是。

**Comment by X140Yu** [comment]
@ghost320 [Download](https://github.com/SwiftGGTeam/Developing-iOS-9-Apps-with-Swift/blob/master/download.md)
