### ISSUE TITLE
求大神们快点翻译吧~~

### ISSUE THREAD

**Issue by panjiulong** [X140Yu/Developing-iOS-9-Apps-with-Swift#39]
等了好久好久咯~

**Comment by Vernsu** [comment]
你可以先去看iOS 8 的教程。
按目前这个翻译进度，你可能有的等了。
swift教程和社区，去年热闹了一年，今年冷清了太多。

**Comment by Latias94** [comment]
硬啃吧，这视频是英文而不看就太可惜了。

**Comment by saitjr** [comment]
字幕翻译确实有点慢，人手也不怎够，不过我们会尽力而为的。
为了有一个纯净的翻译任务列表，要关掉此 issue 了，请谅解。
