### ISSUE TITLE
Can I upload your translations to Youtube?

### ISSUE THREAD

**Issue by Hopsken** [X140Yu/Developing-iOS-9-Apps-with-Swift#40]
There is a channel in Youtube that contains all these videos, but sadly not each of them have Chinese Simplified subtitles. So, I am wondering if I can upload your translations to Youtube to help more people who want to learn iOS on Youtube.
Best regards.

**Comment by daybreak1024** [comment]
sorry。my English is so bad。so I can't help u

Sent from Mail Master
On 09/25/2016 14:35, Hopsken wrote:

There is a channel in Youtube that contains all these videos, but sadly not each of them have Chinese Simplified subtitles. So, I am wondering if I can upload your translations to Youtube to help more people who want to learn iOS on Youtube.
Best regards.

**Comment by Hopsken** [comment]
额，其实我就是想问一下我能不能把你们翻译的字幕放到YouTube上面？

**Comment by X140Yu** [comment]
可是并没有翻译完啊……

**Comment by Hopsken** [comment]
但是已经有几章翻译完了啊

**Comment by X140Yu** [comment]
Feel free to use it, dont forget to add this repo's links to the video description.  :)

**Comment by Vernsu** [comment]
这个中英混杂的对话让我想笑 - -

**Comment by X140Yu** [comment]
这叫首尾呼应(´･ω･`)
