### ISSUE TITLE
「感谢」感谢这个项目的发起

### ISSUE THREAD

**Issue by Vernsu** [X140Yu/Developing-iOS-9-Apps-with-Swift#41]
我一向畏惧啃生肉，觉得自己不可能看懂比较长的英文视频，所以最初是因为本项目的发起才开始看CS193P 2016的。

看到第五节的时候中文字幕中断，我只好开始等待，漫长的等待。等到后来终于发现如果想要学完这套教程，只能自己硬起头皮来啃。

现在，我看到了第14集，还剩4节课就完成了这套教程。

重要的是，现在我对观看英文视频怯意大消，对阅读英文文章与资讯感觉顺理成章。这是我最大的收获。

感谢@X140Yu组织发起了本项目，并提供英文字幕。
感谢前几节课的翻译者与校对者。

**Comment by X140Yu** [comment]
@Vernsu 要感谢应该感谢课程的讲师 Paul，感谢他把课程设置的这么好。

其次你应该感谢你自己。现在开发行业竞争这么激烈，掌握英语对于每一个行业人员来说都应当是必要的。你突破了这一关才能保证自己能够及时了解到行业的最新动态，学习到最新的知识（而不是等翻译）。

而我（们）呢，只做了一点微小的贡献，做一半还弃坑了，有什么可感谢的 😂
