### ISSUE TITLE
大神们没有更新了吗😭

### ISSUE THREAD

**Issue by ganjmeng** [X140Yu/Developing-iOS-9-Apps-with-Swift#43]
大神们没有更新了吗😭

**Comment by kkLee** [comment]
看到第3课发现没字幕了。有好心人来翻译吗

**Comment by X140Yu** [comment]
如果很着急的话可以先看 [iOS 8 的](https://github.com/SwiftGGTeam/Developing_iOS_8_Apps_With_Swift)， 差别不是很大
