### ISSUE TITLE
請問會翻譯iOS10嗎？

### ISSUE THREAD

**Issue by powerwolf543** [X140Yu/Developing-iOS-9-Apps-with-Swift#56]
最近有iOS10出來了
不知道貴團隊有計劃翻譯iOS的部分嗎？

**Comment by ApolloZhu** [comment]
如果您有兴趣，可以关注下 https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift
虽然目前只有我一个学生在缓慢地翻译

**Comment by buginux** [comment]
现在人手不足，都跟不上原版更新速度了。囧。

**Comment by saitjr** [comment]
iOS 10 目前美团开发组正在跟进，如果版权没问题，应该会翻译

**Comment by ApolloZhu** [comment]
有美团的链接么？

**Comment by SwiftSIQI** [comment]
@ApolloZhu 目前还没有为 iOS 10 开仓库，正在处理授权的相关事宜。相关事宜可以关注 SwiftGG 的动态

**Comment by HaozhongChen** [comment]
@ApolloZhu 请问你们说的美团是指什么呀？

**Comment by ApolloZhu** [comment]
我也想知道 @saitjr

**Comment by saitjr** [comment]
还有别的美团吗 🤔

**Comment by ApolloZhu** [comment]
跟进是什么意思？有链接么 @saitjr

**Comment by ApolloZhu** [comment]
悲伤的故事，出 iOS 11 了
https://github.com/ApolloZhu/Developing-iOS-11-Apps-with-Swift
